### ISSUE TITLE
[Question] [PureBoot] GCC 12/ld 2.38 build

### ISSUE THREAD

**Issue by Unb0rn** [osresearch/heads#1192]
Hello! I was trying to build Heads (Well, to be precise PureBoot fork) on Arch with GCC 12 and it seems to fail.
First, I had to patch the kernel with the mainlined patch:
subcmd-util.h:
```
--- a/tools/lib/subcmd/subcmd-util.h
+++ b/tools/lib/subcmd/subcmd-util.h
@@ -50,15 +50,8 @@  static NORETURN inline void die(const ch
 static inline void *xrealloc(void *ptr, size_t size)
 {
 	void *ret = realloc(ptr, size);
-	if (!ret && !size)
-		ret = realloc(ptr, 1);
-	if (!ret) {
-		ret = realloc(ptr, size);
-		if (!ret && !size)
-			ret = realloc(ptr, 1);
-		if (!ret)
-			die("Out of memory, realloc failed");
-	}
+	if (!ret)
+		die("Out of memory, realloc failed");
 	return ret;
 }
```
Now the kernel will build, but when it comes to cryptsetup2 there seem to be an issue with linker:
```
/opt/pureboot/crossgcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: warning: libc.so.6, needed by //lib/libpopt.so, not found (try using -rpath or -rpath-link)
/opt/pureboot/crossgcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: warning: ld-linux-x86-64.so.2, needed by /opt/pureboot/install/lib/libblkid.so, not found (try using -rpath or -rpath-link)
/opt/pureboot/crossgcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: //lib/libpopt.so: undefined reference to `nl_langinfo@GLIBC_2.2.5'
/opt/pureboot/crossgcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /opt/pureboot/install/lib/libblkid.so: undefined reference to `strtol@GLIBC_2.2.5'
/opt/pureboot/crossgcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: //lib/libpopt.so: undefined reference to `free@GLIBC_2.2.5'
```
And so on...
Are there any plans to migrate to GCC12? Maybe some known workarounds? Thanks!

**Comment by tlaurion** [comment]
@Unb0rn For some reason, it seems that for your extract, muslc libc.so that is first built and copied over install  is not being looked for by modules you are building and that general gcc libc is searched for instead but not-found.

Rebuilding clean here on debian-11 to make sure that everything is still clean, while CircleCI has built clean recently from debian-11 without failing, while local gawk and local make build were removed recently, and while CircleCI `make BOARD=desired_board bootstrap` was also removed.

Can you point out how you are building @Unb0rn?

**Comment by tlaurion** [comment]
@JonathonHall-Purism: any insights?

**Comment by tlaurion** [comment]
@JonathonHall-Purism: any insights?

**Comment by tlaurion** [comment]
@Unb0rn a general not is that Heads is built on CI by debian-11 without issue.

**Comment by Unb0rn** [comment]
@tlaurion Yeah, it builds fine on Ubuntu (at least 20.04), but usually I use Arch in podman container to build everything.
It was fairly simple to fix cross toolchain building with [this patch](https://review.coreboot.org/c/coreboot/+/65000/) so coreboot without payload builds fine (and is actually my daily driver now). 
It was also simple to fix Linux kernel build with GCC 12 using this [upstreamed patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/tools/lib/subcmd/subcmd-util.h?id=52a9dab6d892763b2a8334a568bd4e2c1a6fde66)

So I thought maybe I can build everything in my familiar environment on Arch, but yeah, linker gets stuck on musl libc. I thought it could be version-related, and if so it should be fixed sooner or later. But if the problem is not gcc 12.1 then maybe we should close this issue and just continue building on Ubuntu/Debian =)

**Comment by tlaurion** [comment]
@Unb0rn PR welcome, but understanding that its impossible to maintain for all oses should be understood which is why docker image based on NixOs is desired.

Is your patch not causing regression over debian-11/20.04? If answer is yes, then PR welcome.

Otherwise, please close issue since won't fix.

**Comment by Unb0rn** [comment]
Yep, I think you're right. It would be wiser just to have some standard way of building than supporting myriad of envs. Closing this. Thanks!
